export enum AlertType {
  GEOFENCE_ENTRY = 'GEOFENCE_ENTRY',
  GEOFENCE_EXIT = 'GEOFENCE_EXIT',
  OVERSPEED = 'OVERSPEED',
  LOW_BATTERY = 'LOW_BATTERY',
  DEVICE_OFFLINE = 'DEVICE_OFFLINE',
  MAINTENANCE = 'MAINTENANCE',
  CUSTOM = 'CUSTOM',
}

export enum AlertSeverity {
  CRITICAL = 'CRITICAL',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
  INFO = 'INFO',
}
